"""Generate chipstone_title_fixes.sql from chipstone_raw.json + D1 card IDs."""
import io, json, re, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

SKIP_TITLES = {"book reviews", "the chipstone foundation", "annual bibliography"}

def split_author_title(raw_title):
    card_type = "article"
    text = raw_title.strip()
    if text.lower().rstrip(".") in SKIP_TITLES:
        return None, raw_title, card_type
    if text.lower().startswith("review by "):
        card_type = "review"
        text = text[len("review by "):]
    text = re.sub(r"(Jr|Sr)\.\*", r"\1.", text)
    candidates = []
    for m in re.finditer(r"(?:Jr|Sr)\.[A-Z]", text):
        candidates.append((m.start() + len(m.group()) - 1, "jr_period"))
    for m in re.finditer(r"(?<!\w)(?:IV|III|II(?!I))(?=[A-Z])", text):
        candidates.append((m.end(), "roman"))
    for m in re.finditer(r'[a-z](?=["\u201c\u201d])', text):
        candidates.append((m.start() + 1, "quote"))
    for m in re.finditer(r"[a-z](?=[A-Z])", text):
        candidates.append((m.start() + 1, "lc_uc"))
    if not candidates:
        return [], raw_title, card_type
    candidates.sort(key=lambda x: x[0])
    pos, _ = candidates[0]
    author_str = text[:pos].rstrip(",").strip()
    title = text[pos:].strip()
    if len(author_str) < 4 or len(title) < 5:
        return [], raw_title, card_type
    author_str_norm = re.sub(r",\s*(Jr|Sr|II|III|IV)\.?", r" \1.", author_str)
    authors = [a.strip() for a in re.split(r",?\s+and\s+|,\s*", author_str_norm) if a.strip()]
    return authors, title, card_type


def esc(s):
    return str(s).replace("'", "''") if s else ""


# Load raw scrape data (keyed by URL)
with open("chipstone_raw.json", encoding="utf-8") as f:
    raw = json.load(f)
raw_by_url = {r["url"]: r for r in raw}

# Load card IDs from DB export (chipstone_cards.json has view_url)
with open("chipstone_cards.json", encoding="utf-8") as f:
    cards = json.load(f)

lines = [
    "-- Chipstone title/author fix — generated by gen_title_fix_sql.py",
    "-- Splits concatenated 'AuthorNameTitle' into separate fields",
    "",
]

ok = skipped = problems = 0

# We need IDs — query D1 first and save, OR join by view_url at runtime.
# Since chipstone_cards.json has view_url, we generate parameterised UPDATEs
# that match on view_url (unique per article).

for card in cards:
    view_url = card.get("view_url", "")
    raw_rec = raw_by_url.get(view_url)
    if not raw_rec:
        continue

    authors, title, card_type = split_author_title(raw_rec["title"])

    if authors is None:
        skipped += 1
        continue
    if not authors:
        problems += 1
        lines.append(f"-- PROBLEM (no split): {raw_rec['title'][:80]}")
        continue

    authors_json = json.dumps(authors, ensure_ascii=False)
    lines.append(
        f"UPDATE library_cards SET "
        f"title = '{esc(title)}', "
        f"authors = '{esc(authors_json)}', "
        f"card_type = '{card_type}', "
        f"updated_at = datetime('now') "
        f"WHERE source_key = 'chipstone' AND view_url = '{esc(view_url)}';"
    )
    ok += 1

# Handle the one known anonymous record manually
lines.append("")
lines.append("-- Manual fix: anonymous document")
lines.append(
    "UPDATE library_cards SET "
    "title = 'The Notebook of Philadelphia Joiner John Widdifield', "
    "authors = '[\"Anonymous\"]', card_type = 'article', updated_at = datetime('now') "
    "WHERE source_key = 'chipstone' AND title LIKE '%Widdifield%';"
)

with open("chipstone_title_fixes.sql", "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"SQL written: {ok} updates, {skipped} skipped (headers), {problems} problems")
print("Output: chipstone_title_fixes.sql")
